services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: API_URL
        value: https://backend.onrender.com

databases:
  - name: mydb
    plan: free
