"""Added audit columns

Revision ID: d0411fc5a28b
Revises: a9915dfeefd5
Create Date: 2025-05-14 17:45:34.779907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0411fc5a28b'
down_revision: Union[str, None] = 'a9915dfeefd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_years', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=True))
    op.add_column('academic_years', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('academic_years', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('academic_years', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('academic_years', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('auto_management', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=True))
    op.add_column('auto_management', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('auto_management', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('auto_management', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('auto_management', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('classes', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=True))
    op.add_column('classes', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('classes', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('classes', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('classes', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('fee_payments', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=True))
    op.add_column('fee_payments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('fee_payments', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('fee_payments', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('fee_payments', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('sections', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=True))
    op.add_column('sections', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('sections', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('sections', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('sections', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('status', sa.Enum('ACTIVE', 'DROPPED_OFF', 'ARCHIVED', 'DELETED', name='studentstatus'), nullable=True))
    op.add_column('students', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('students', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('students', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('students', 'day_boarding_fees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('day_boarding_fees', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('students', 'updated_date')
    op.drop_column('students', 'created_date')
    op.drop_column('students', 'updated_by')
    op.drop_column('students', 'created_by')
    op.drop_column('students', 'status')
    op.drop_column('sections', 'updated_date')
    op.drop_column('sections', 'created_date')
    op.drop_column('sections', 'updated_by')
    op.drop_column('sections', 'created_by')
    op.drop_column('sections', 'status')
    op.drop_column('fee_payments', 'updated_date')
    op.drop_column('fee_payments', 'created_date')
    op.drop_column('fee_payments', 'updated_by')
    op.drop_column('fee_payments', 'created_by')
    op.drop_column('fee_payments', 'status')
    op.drop_column('classes', 'updated_date')
    op.drop_column('classes', 'created_date')
    op.drop_column('classes', 'updated_by')
    op.drop_column('classes', 'created_by')
    op.drop_column('classes', 'status')
    op.drop_column('auto_management', 'updated_date')
    op.drop_column('auto_management', 'created_date')
    op.drop_column('auto_management', 'updated_by')
    op.drop_column('auto_management', 'created_by')
    op.drop_column('auto_management', 'status')
    op.drop_column('academic_years', 'updated_date')
    op.drop_column('academic_years', 'created_date')
    op.drop_column('academic_years', 'updated_by')
    op.drop_column('academic_years', 'created_by')
    op.drop_column('academic_years', 'status')
    # ### end Alembic commands ###
